// ─────────────────────────────────────────────────────────────────────────────
// EA CRM — Role type hierarchy and ALL apprenticeship standards
// Auto-generated from DfE standards register — April 2026
// 710 standards across 15 routes
// ─────────────────────────────────────────────────────────────────────────────

export const ROLE_TYPE_HIERARCHY: Record<string, { hasStandards: boolean; subTypes: string[] }> = {
  'Delivery': {
    hasStandards: true,
    subTypes: [
      'Assessor', 'IQA', 'Lead IQA', 'End-Point Assessor (EPA)',
      'Skills Coach', 'Tutor / Trainer', 'Employability Tutor', 'Distance Learning Tutor',
      'Workshop Facilitator', 'Vocational Trainer',
      'Functional Skills Tutor (Maths)', 'Functional Skills Tutor (English)',
      'Learning Support Worker',
    ],
  },
  'Quality & Curriculum': {
    hasStandards: false,
    subTypes: [
      'Curriculum Manager', 'Curriculum Developer', 'Qualification Developer',
      'E-Learning Developer', 'Quality Manager', 'Compliance Manager',
      'Ofsted Nominee', 'Head of Quality', 'EPA Centre Coordinator', 'CEIAG Adviser',
    ],
  },
  'Commercial': {
    hasStandards: false,
    subTypes: [
      'Business Development Manager', 'Employment Specialist', 'Employer Engagement Manager',
      'Apprenticeship Advisor', 'Recruitment Consultant', 'Partnerships Manager',
      'Account Manager', 'Key Account Manager', 'Bid Writer',
      'Marketing Manager', 'Apprenticeship Levy Consultant',
    ],
  },
  'Operations': {
    hasStandards: false,
    subTypes: [
      'Operations Manager', 'Centre Manager', 'Programme Manager',
      'Regional Manager', 'Training Coordinator', 'Learner Services Manager',
      'Timetabling / Scheduling Manager', 'Contract Manager',
      'Functional Skills Coordinator',
    ],
  },
  'Leadership': {
    hasStandards: false,
    subTypes: [
      'Head of Department', 'Head of Apprenticeships', 'Head of Commercial',
      'Assistant Principal', 'Vice Principal', 'Director of Education',
      'Director of Quality', 'Director of Business Development', 'Principal', 'CEO / MD',
    ],
  },
  'Data & Admin': {
    hasStandards: false,
    subTypes: [
      'MIS Officer', 'MIS Manager', 'Data Analyst', 'Apprenticeship Administrator',
      'Learner Records Officer', 'Funding & Compliance Officer',
      'Exams Officer', 'Finance Manager', 'HR Manager',
    ],
  },
}

export const MAIN_ROLE_TYPES = Object.keys(ROLE_TYPE_HIERARCHY)

export type Standard = { name: string; level: number; ref: string }
export type StandardsRoute = { route: string; standards: Standard[] }

export const APPRENTICESHIP_STANDARDS: StandardsRoute[] = [
  {
    route: 'Engineering and manufacturing',
    standards: [
      { name: 'Abattoir worker', level: 2, ref: 'ST0418' },
      { name: 'Autocare technician', level: 2, ref: 'ST0499' },
      { name: 'Aviation maintenance mechanic', level: 2, ref: 'ST0014' },
      { name: 'Bicycle mechanic', level: 2, ref: 'ST0622' },
      { name: 'Commercial laundry operative', level: 2, ref: 'ST0604' },
      { name: 'Construction equipment maintenance mechanic', level: 2, ref: 'ST0805' },
      { name: 'Drainage network operative', level: 2, ref: 'ST1348' },
      { name: 'Engineering operative', level: 2, ref: 'ST0537' },
      { name: 'Fenestration fabricator', level: 2, ref: 'ST0744' },
      { name: 'Food and drink process operator', level: 2, ref: 'ST0199' },
      { name: 'Footwear manufacturer', level: 2, ref: 'ST0202' },
      { name: 'Furniture finisher', level: 2, ref: 'ST0977' },
      { name: 'Furniture making operative', level: 2, ref: 'ST0982' },
      { name: 'Furniture manufacturer', level: 2, ref: 'ST0203' },
      { name: 'Gas network operative', level: 2, ref: 'ST0204' },
      { name: 'Lean manufacturing operative', level: 2, ref: 'ST0420' },
      { name: 'Maritime mechanical and electrical mechanic', level: 2, ref: 'ST0276' },
      { name: 'Material cutter', level: 2, ref: 'ST0899' },
      { name: 'Material processing plant operator', level: 2, ref: 'ST0144' },
      { name: 'Mattress manufacturing operative', level: 2, ref: 'ST0981' },
      { name: 'Metal recycling general operative', level: 2, ref: 'ST0507' },
      { name: 'Mineral and construction product sampling and testing operations', level: 2, ref: 'ST0511' },
      { name: 'Non-destructive testing (NDT) operator', level: 2, ref: 'ST0358' },
      { name: 'Nuclear health physics monitor', level: 2, ref: 'ST0290' },
      { name: 'Nuclear operative', level: 2, ref: 'ST0291' },
      { name: 'Print operative', level: 2, ref: 'ST0962' },
      { name: 'Rail engineering operative', level: 2, ref: 'ST0317' },
      { name: 'Science manufacturing process operative', level: 2, ref: 'ST0422' },
      { name: 'Sewing machinist', level: 2, ref: 'ST0549' },
      { name: 'Stairlift, platform lift, service lift electromechanic', level: 2, ref: 'ST0251' },
      { name: 'Textile manufacturing operative', level: 2, ref: 'ST0458' },
      { name: 'Upholstery operative', level: 2, ref: 'ST1034' },
      { name: 'Water network operative', level: 2, ref: 'ST0898' },
      { name: 'Water process operative', level: 2, ref: 'ST0876' },
      { name: 'Welder', level: 2, ref: 'ST0349' },
      { name: 'Wood machinist', level: 2, ref: 'ST0976' },
      { name: 'Wood product manufacturing operative', level: 2, ref: 'ST0531' },
      { name: 'Accident repair technician', level: 3, ref: 'ST0352' },
      { name: 'Advanced furniture CNC technician', level: 3, ref: 'ST0655' },
      { name: 'Advanced upholsterer', level: 3, ref: 'ST0656' },
      { name: 'Aerospace engineering technician', level: 3, ref: 'ST1313' },
      { name: 'Aircraft maintenance technician', level: 3, ref: 'ST1315' },
      { name: 'Automotive glazing technician', level: 3, ref: 'ST0031' },
      { name: 'Battery manufacturing technician', level: 3, ref: 'ST1338' },
      { name: 'Boatbuilder', level: 3, ref: 'ST0059' },
      { name: 'Bulk storage terminal technician', level: 3, ref: 'ST1339' },
      { name: 'Bus and coach engineering technician', level: 3, ref: 'ST0067' },
      { name: 'Commercial catering equipment technician', level: 3, ref: 'ST0791' },
      { name: 'Composites technician', level: 3, ref: 'ST0094' },
      { name: 'Compressed air and vacuum technician', level: 3, ref: 'ST0817' },
      { name: 'Construction equipment maintenance technician', level: 3, ref: 'ST0671' },
      { name: 'Drinks dispense technician', level: 3, ref: 'ST0752' },
      { name: 'Electrical, electronic product service and installation engineer', level: 3, ref: 'ST0150' },
      { name: 'Engineering and manufacturing support technician', level: 3, ref: 'ST1395' },
      { name: 'Engineering design technician', level: 3, ref: 'ST0164' },
      { name: 'Engineering fitter', level: 3, ref: 'ST0432' },
      { name: 'Engineering maintenance technician - dual discipline', level: 3, ref: 'ST1443' },
      { name: 'Engineering maintenance technician - single discipline', level: 3, ref: 'ST1426' },
      { name: 'Engineering technician', level: 3, ref: 'ST0457' },
      { name: 'Fitted furniture design technician', level: 3, ref: 'ST0654' },
      { name: 'Food and drink maintenance engineer', level: 3, ref: 'ST0195' },
      { name: 'Food and drink technical operator', level: 3, ref: 'ST0196' },
      { name: 'Gas network craftsperson', level: 3, ref: 'ST0205' },
      { name: 'Healthcare engineering specialist technician', level: 3, ref: 'ST0950' },
      { name: 'Heat network maintenance technician', level: 3, ref: 'ST1308' },
      { name: 'Heavy vehicle service and maintenance technician', level: 3, ref: 'ST0068' },
      { name: 'Heritage engineering technician', level: 3, ref: 'ST0571' },
      { name: 'Lift and escalator engineering', level: 3, ref: 'ST0252' },
      { name: 'Lift truck and powered access engineering technician', level: 3, ref: 'ST0387' },
      { name: 'Lifting equipment technician', level: 3, ref: 'ST0872' },
      { name: 'Machining technician', level: 3, ref: 'ST1305' },
      { name: 'Maintenance and operations engineering technician', level: 3, ref: 'ST0154' },
      { name: 'Marine electrician', level: 3, ref: 'ST0808' },
      { name: 'Marine engineer', level: 3, ref: 'ST0364' },
      { name: 'Maritime electrical fitter', level: 3, ref: 'ST1403' },
      { name: 'Maritime mechanical fitter', level: 3, ref: 'ST1402' },
      { name: 'Maritime pipeworker', level: 3, ref: 'ST1391' },
      { name: 'Mechatronics maintenance technician', level: 3, ref: 'ST1326' },
      { name: 'Metal casting, foundry and patternmaking technician', level: 3, ref: 'ST0566' },
      { name: 'Metal fabricator', level: 3, ref: 'ST0607' },
      { name: 'Mobile transport refrigeration technician', level: 3, ref: 'ST1327' },
      { name: 'Motor vehicle service and maintenance technician - light vehicle', level: 3, ref: 'ST0033' },
      { name: 'Motorcycle technician (repair and maintenance)', level: 3, ref: 'ST0376' },
      { name: 'Non-destructive technologies technician', level: 3, ref: 'ST0288' },
      { name: 'Pipe welder', level: 3, ref: 'ST0851' },
      { name: 'Plate welder', level: 3, ref: 'ST0852' },
      { name: 'Polymer processing technician', level: 3, ref: 'ST1328' },
      { name: 'Power industry distribution cable jointer', level: 3, ref: 'ST1332' },
      { name: 'Power industry overhead linesperson', level: 3, ref: 'ST1330' },
      { name: 'Power industry substation fitter', level: 3, ref: 'ST1331' },
      { name: 'Print technician', level: 3, ref: 'ST0309' },
      { name: 'Process industry manufacturing technician', level: 3, ref: 'ST1407' },
      { name: 'Project controls technician', level: 3, ref: 'ST0163' },
      { name: 'Rail engineering technician', level: 3, ref: 'ST0318' },
      { name: 'Railway engineering design technician', level: 3, ref: 'ST0315' },
      { name: 'Science manufacturing technician 2023', level: 3, ref: 'ST1406' },
      { name: 'Signage technician', level: 3, ref: 'ST0824' },
      { name: 'Spectacle technician', level: 3, ref: 'ST0383' },
      { name: 'Surface finisher', level: 3, ref: 'ST0963' },
      { name: 'Survival equipment fitter', level: 3, ref: 'ST0015' },
      { name: 'Toolmaker and tool and die maintenance technician', level: 3, ref: 'ST1370' },
      { name: 'Vehicle damage mechanical, electrical and trim (MET) technician', level: 3, ref: 'ST0405' },
      { name: 'Vehicle damage paint technician', level: 3, ref: 'ST0448' },
      { name: 'Vehicle damage panel technician', level: 3, ref: 'ST0403' },
      { name: 'Water industry asset maintenance technician', level: 3, ref: 'ST1404' },
      { name: 'Water industry network technician', level: 3, ref: 'ST1292' },
      { name: 'Water industry treatment process technician', level: 3, ref: 'ST1291' },
      { name: 'Water treatment technician', level: 3, ref: 'ST0453' },
      { name: 'Wind turbine maintenance technician', level: 3, ref: 'ST1455' },
      { name: 'Asset manager', level: 4, ref: 'ST0861' },
      { name: 'Automation and controls engineering technician', level: 4, ref: 'ST0662' },
      { name: 'Brewer', level: 4, ref: 'ST0580' },
      { name: 'Electrical power networks engineer', level: 4, ref: 'ST0475' },
      { name: 'Electrical power protection and plant commissioning engineer', level: 4, ref: 'ST0157' },
      { name: 'Engineer surveyor', level: 4, ref: 'ST0847' },
      { name: 'Engineering manufacturing technician', level: 4, ref: 'ST0841' },
      { name: 'Fashion and textiles product technologist', level: 4, ref: 'ST0540' },
      { name: 'Lead engineering maintenance technician', level: 4, ref: 'ST0999' },
      { name: 'Nuclear welding inspection technician', level: 4, ref: 'ST0292' },
      { name: 'Ordnance munitions explosives technician', level: 4, ref: 'ST0833' },
      { name: 'Process leader', level: 4, ref: 'ST0695' },
      { name: 'Propulsion technician', level: 4, ref: 'ST0588' },
      { name: 'Quarrying and mining blasting operations technician', level: 4, ref: 'ST1451' },
      { name: 'Rail engineering advanced technician', level: 4, ref: 'ST0316' },
      { name: 'Small vessel chief engineer', level: 4, ref: 'ST0875' },
      { name: 'Textile technical specialist', level: 4, ref: 'ST0581' },
      { name: 'Vehicle damage assessor', level: 4, ref: 'ST0406' },
      { name: 'Water operations manager', level: 4, ref: 'ST1453' },
      { name: 'Food and drink engineer', level: 5, ref: 'ST0624' },
      { name: 'Mineral products technician', level: 5, ref: 'ST0605' },
      { name: 'Nuclear technician', level: 5, ref: 'ST0380' },
      { name: 'Aerospace engineer', level: 6, ref: 'ST0010' },
      { name: 'Control systems engineer (degree)', level: 6, ref: 'ST0023' },
      { name: 'Electrical and electronic engineer (degree)', level: 6, ref: 'ST0024' },
      { name: 'Electro-mechanical engineer', level: 6, ref: 'ST0672' },
      { name: 'Embedded electronic systems design and development engineer (degree)', level: 6, ref: 'ST0151' },
      { name: 'Food and drink advanced engineer (integrated degree)', level: 6, ref: 'ST0529' },
      { name: 'High integrity software engineer', level: 6, ref: 'ST0013' },
      { name: 'Manufacturing engineer (degree)', level: 6, ref: 'ST0025' },
      { name: 'Manufacturing manager (integrated degree)', level: 6, ref: 'ST0515' },
      { name: 'Materials science technologist (degree)', level: 6, ref: 'ST0675' },
      { name: 'Mine management', level: 6, ref: 'ST1309' },
      { name: 'Naval architect', level: 6, ref: 'ST0897' },
      { name: 'Non-destructive testing engineer (degree)', level: 6, ref: 'ST0369' },
      { name: 'Nuclear scientist and nuclear engineer (integrated degree)', level: 6, ref: 'ST0289' },
      { name: 'Ordnance munitions and explosives (OME) professional (integrated degree)', level: 6, ref: 'ST0574' },
      { name: 'Packaging professional (integrated degree)', level: 6, ref: 'ST0637' },
      { name: 'Product design and development engineer (degree)', level: 6, ref: 'ST0027' },
      { name: 'Project controls professional', level: 6, ref: 'ST0845' },
      { name: 'Rail and rail systems senior engineer (integrated degree)', level: 6, ref: 'ST0496' },
      { name: 'Robotics engineer - degree', level: 6, ref: 'ST1317' },
      { name: 'Science industry process and plant engineer (degree)', level: 6, ref: 'ST0473' },
      { name: 'Space systems engineer', level: 6, ref: 'ST0856' },
      { name: 'Systems engineer (integrated degree)', level: 6, ref: 'ST1478' },
      { name: 'Digital manufacturing engineering leader', level: 7, ref: 'ST1376' },
      { name: 'Geotechnical engineer (integrated degree)', level: 7, ref: 'ST0881' },
      { name: 'Human factors specialist', level: 7, ref: 'ST0785' },
      { name: 'Infrastructure asset management professional', level: 7, ref: 'ST0860' },
      { name: 'Materials process engineer (degree)', level: 7, ref: 'ST0659' },
      { name: 'Ordnance munitions and explosives specialist (integrated degree)', level: 7, ref: 'ST0834' },
      { name: 'Post graduate engineer', level: 7, ref: 'ST0456' },
      { name: 'Rail and rail systems principal engineer (integrated degree)', level: 7, ref: 'ST0497' },
      { name: 'Risk and safety management professional (degree)', level: 7, ref: 'ST0465' },
      { name: 'Systems engineer (degree)', level: 7, ref: 'ST0107' },
      { name: 'Through life engineering services specialist (integrated degree)', level: 7, ref: 'ST0740' },
      { name: 'Tunnel engineer (degree)', level: 7, ref: 'ST1344' },
    ],
  },
  {
    route: 'Construction and the built environment',
    standards: [
      { name: 'Bricklayer', level: 2, ref: 'ST0095' },
      { name: 'Building services engineering installer', level: 2, ref: 'ST0065' },
      { name: 'Carpentry and joinery', level: 2, ref: 'ST0264' },
      { name: 'Commercial thermal insulation operative', level: 2, ref: 'ST0333' },
      { name: 'Construction assembly and installation operative', level: 2, ref: 'ST0265' },
      { name: 'Construction plant operative', level: 2, ref: 'ST0736' },
      { name: 'Demolition operative', level: 2, ref: 'ST0615' },
      { name: 'Dual fuel smart meter installer', level: 2, ref: 'ST0158' },
      { name: 'Facilities services operative', level: 2, ref: 'ST0617' },
      { name: 'Fencing installer', level: 2, ref: 'ST0366' },
      { name: 'Fenestration installer', level: 2, ref: 'ST0743' },
      { name: 'Fitted interiors installer', level: 2, ref: 'ST0980' },
      { name: 'Floorlayer - textile and resilient', level: 2, ref: 'ST0504' },
      { name: 'Floorlayer wood based', level: 2, ref: 'ST1498' },
      { name: 'Formworker', level: 2, ref: 'ST0461' },
      { name: 'Groundworker', level: 2, ref: 'ST0513' },
      { name: 'Highway electrical maintenance and installation operative', level: 2, ref: 'ST0051' },
      { name: 'Highways maintenance skilled operative', level: 2, ref: 'ST0053' },
      { name: 'Hire controller (plant, tools and equipment)', level: 2, ref: 'ST0269' },
      { name: 'Insulation installation operative', level: 2, ref: 'ST1480' },
      { name: 'Interior systems installer', level: 2, ref: 'ST0388' },
      { name: 'Lead traffic management operative', level: 2, ref: 'ST0985' },
      { name: 'Lifting technician', level: 2, ref: 'ST0267' },
      { name: 'Lightning protection operative', level: 2, ref: 'ST0651' },
      { name: 'Mastic asphalter', level: 2, ref: 'ST0750' },
      { name: 'Painter and decorator', level: 2, ref: 'ST0295' },
      { name: 'Piling attendant', level: 2, ref: 'ST0268' },
      { name: 'Plasterer', level: 2, ref: 'ST0096' },
      { name: 'Powered pedestrian door installer and service engineer', level: 2, ref: 'ST0373' },
      { name: 'Property maintenance operative', level: 2, ref: 'ST0171' },
      { name: 'Road surfacing operative', level: 2, ref: 'ST0693' },
      { name: 'Roofer', level: 2, ref: 'ST0270' },
      { name: 'Scaffolder', level: 2, ref: 'ST0359' },
      { name: 'Steel fixer', level: 2, ref: 'ST0271' },
      { name: 'Steeplejack', level: 2, ref: 'ST1342' },
      { name: 'Stonemason', level: 2, ref: 'ST0442' },
      { name: 'Telecoms field operative', level: 2, ref: 'ST0832' },
      { name: 'Thatcher', level: 2, ref: 'ST0821' },
      { name: 'Wall and floor tiler', level: 2, ref: 'ST0368' },
      { name: 'Wireless communications rigger', level: 2, ref: 'ST0616' },
      { name: 'Building services engineering craftsperson', level: 3, ref: 'ST0062' },
      { name: 'Building services engineering service and maintenance engineer', level: 3, ref: 'ST0061' },
      { name: 'Building services engineering technician 2022', level: 3, ref: 'ST0063' },
      { name: 'Civil engineering technician', level: 3, ref: 'ST0091' },
      { name: 'Construction support technician', level: 3, ref: 'ST0960' },
      { name: 'Craft bricklayer', level: 3, ref: 'ST1334' },
      { name: 'Craft carpentry and joinery', level: 3, ref: 'ST0263' },
      { name: 'Craft painter and decorator', level: 3, ref: 'ST1358' },
      { name: 'Craft plasterer', level: 3, ref: 'ST1385' },
      { name: 'Curtain wall installer', level: 3, ref: 'ST0802' },
      { name: 'Digital engineering technician', level: 3, ref: 'ST0266' },
      { name: 'Domestic electrician', level: 3, ref: 'ST1017' },
      { name: 'Energy manager', level: 3, ref: 'ST0161' },
      { name: 'Engineering construction erector rigger', level: 3, ref: 'ST0433' },
      { name: 'Engineering construction pipefitter', level: 3, ref: 'ST0162' },
      { name: 'Facilities management supervisor', level: 3, ref: 'ST0170' },
      { name: 'Fall protection technician', level: 3, ref: 'ST0614' },
      { name: 'Fire emergency and security systems technician', level: 3, ref: 'ST0189' },
      { name: 'Gas engineering operative', level: 3, ref: 'ST0155' },
      { name: 'Geospatial survey technician', level: 3, ref: 'ST0491' },
      { name: 'Highways electrician or service operative', level: 3, ref: 'ST0052' },
      { name: 'Industrial thermal insulation technician', level: 3, ref: 'ST0521' },
      { name: 'Installation and maintenance electrician', level: 3, ref: 'ST0152' },
      { name: 'Insulation technician', level: 3, ref: 'ST1396' },
      { name: 'Landscape technician', level: 3, ref: 'ST0741' },
      { name: 'Low carbon heating technician', level: 3, ref: 'ST1020' },
      { name: 'Military engineering construction technician', level: 3, ref: 'ST0414' },
      { name: 'Plumbing and domestic heating technician', level: 3, ref: 'ST0303' },
      { name: 'Refrigeration air conditioning and heat pump engineering technician', level: 3, ref: 'ST0322' },
      { name: 'Smart home technician', level: 3, ref: 'ST0464' },
      { name: 'Surveying technician', level: 3, ref: 'ST0332' },
      { name: 'Transport planning technician', level: 3, ref: 'ST0336' },
      { name: 'BEMS (building energy management systems) controls engineer', level: 4, ref: 'ST0629' },
      { name: 'Building services engineering senior technician', level: 4, ref: 'ST0041' },
      { name: 'CNFE - Cellular network field engineer', level: 4, ref: 'ST1299' },
      { name: 'Civil engineering senior technician', level: 4, ref: 'ST0046' },
      { name: 'Construction design and build technician', level: 4, ref: 'ST0043' },
      { name: 'Construction quantity surveying technician', level: 4, ref: 'ST0049' },
      { name: 'Construction site supervisor', level: 4, ref: 'ST0048' },
      { name: 'Facilities manager', level: 4, ref: 'ST0484' },
      { name: 'Town planning assistant', level: 4, ref: 'ST0936' },
      { name: 'Retrofit coordinator', level: 5, ref: 'ST1375' },
      { name: 'Architectural assistant (integrated degree)', level: 6, ref: 'ST0534' },
      { name: 'Building control surveyor (integrated degree)', level: 6, ref: 'ST0652' },
      { name: 'Building services engineer', level: 6, ref: 'ST0372' },
      { name: 'Chartered surveyor (degree)', level: 6, ref: 'ST0331' },
      { name: 'Civil engineer', level: 6, ref: 'ST0417' },
      { name: 'Construction quantity surveyor (degree)', level: 6, ref: 'ST0045' },
      { name: 'Construction site management (degree)', level: 6, ref: 'ST0047' },
      { name: 'Design and construction management (degree)', level: 6, ref: 'ST0044' },
      { name: 'Fire safety engineer', level: 6, ref: 'ST0859' },
      { name: 'Geospatial mapping and science specialist (degree)', level: 6, ref: 'ST0492' },
      { name: 'Senior and head of facilities management (integrated degree)', level: 6, ref: 'ST0410' },
      { name: 'Transport planner (integrated degree)', level: 6, ref: 'ST0698' },
      { name: 'Architect (integrated degree)', level: 7, ref: 'ST0533' },
      { name: 'Chartered town planner (degree)', level: 7, ref: 'ST0536' },
    ],
  },
  {
    route: 'Health and science',
    standards: [
      { name: 'Cleaning hygiene operative', level: 2, ref: 'ST0843' },
      { name: 'Community activator coach', level: 2, ref: 'ST0478' },
      { name: 'Healthcare science assistant', level: 2, ref: 'ST0218' },
      { name: 'Healthcare support worker', level: 2, ref: 'ST0216' },
      { name: 'Leisure team member', level: 2, ref: 'ST0390' },
      { name: 'Pharmacy services assistant', level: 2, ref: 'ST0299' },
      { name: 'Ambulance support worker (emergency, urgent and non-urgent)', level: 3, ref: 'ST0627' },
      { name: 'Animal technologist', level: 3, ref: 'ST0058' },
      { name: 'Clinical coder', level: 3, ref: 'ST0535' },
      { name: 'Community health and wellbeing worker', level: 3, ref: 'ST0958' },
      { name: 'Community sport and health officer', level: 3, ref: 'ST0093' },
      { name: 'Dental nurse', level: 3, ref: 'ST1431' },
      { name: 'Food industry technologist', level: 3, ref: 'ST0198' },
      { name: 'Laboratory technician', level: 3, ref: 'ST0248' },
      { name: 'Metrology technician', level: 3, ref: 'ST0282' },
      { name: 'Mortuary technician', level: 3, ref: 'ST0889' },
      { name: 'Optical assistant 2022', level: 3, ref: 'ST1377' },
      { name: 'Outdoor activity instructor', level: 3, ref: 'ST0479' },
      { name: 'Peer worker', level: 3, ref: 'ST0896' },
      { name: 'Personal trainer', level: 3, ref: 'ST0302' },
      { name: 'Pharmacy technician (integrated)', level: 3, ref: 'ST0300' },
      { name: 'Prosthetic and orthotic technician', level: 3, ref: 'ST0632' },
      { name: 'Senior healthcare support worker', level: 3, ref: 'ST0217' },
      { name: 'Sporting excellence professional', level: 3, ref: 'ST0524' },
      { name: 'Associate ambulance practitioner', level: 4, ref: 'ST0287' },
      { name: 'Healthcare science associate', level: 4, ref: 'ST0220' },
      { name: 'Hygiene specialist', level: 4, ref: 'ST0873' },
      { name: 'Mammography associate', level: 4, ref: 'ST0583' },
      { name: 'Oral health practitioner', level: 4, ref: 'ST0542' },
      { name: 'Orthodontic therapist', level: 4, ref: 'ST1434' },
      { name: 'Sports coach', level: 4, ref: 'ST0770' },
      { name: 'Assistant practitioner (health)', level: 5, ref: 'ST0215' },
      { name: 'Associate continuing healthcare practitioner', level: 5, ref: 'ST0786' },
      { name: 'Clinical dental technician', level: 5, ref: 'ST1433' },
      { name: 'Dairy technologist', level: 5, ref: 'ST0393' },
      { name: 'Dental technician', level: 5, ref: 'ST1432' },
      { name: 'Embalmer', level: 5, ref: 'ST0890' },
      { name: 'Health play specialist', level: 5, ref: 'ST0829' },
      { name: 'Hearing aid dispenser', level: 5, ref: 'ST0600' },
      { name: 'Nursing associate (NMC 2018)', level: 5, ref: 'ST0827' },
      { name: 'Outdoor learning specialist', level: 5, ref: 'ST0945' },
      { name: 'Technician scientist', level: 5, ref: 'ST0597' },
      { name: 'Vision rehabilitation specialist', level: 5, ref: 'ST0431' },
      { name: 'Biomedical scientist', level: 6, ref: 'ST1314' },
      { name: 'Clinical trials specialist (degree)', level: 6, ref: 'ST0609' },
      { name: 'Diagnostic radiographer', level: 6, ref: 'ST0619' },
      { name: 'Dietitian', level: 6, ref: 'ST0599' },
      { name: 'Dispensing optician', level: 6, ref: 'ST0774' },
      { name: 'Enhanced clinical practitioner', level: 6, ref: 'ST0895' },
      { name: 'Environmental health practitioner (integrated degree)', level: 6, ref: 'ST0714' },
      { name: 'Food industry technical professional (integrated degree)', level: 6, ref: 'ST0197' },
      { name: 'Geoscientist (integrated degree)', level: 6, ref: 'ST1356' },
      { name: 'Healthcare science practitioner (integrated degree)', level: 6, ref: 'ST0413' },
      { name: 'Midwife (2019 NMC standards) (Integrated degree)', level: 6, ref: 'ST0948' },
      { name: 'Occupational therapist', level: 6, ref: 'ST0517' },
      { name: 'Operating department practitioner', level: 6, ref: 'ST0582' },
      { name: 'Orthoptist', level: 6, ref: 'ST1272' },
      { name: 'Paramedic', level: 6, ref: 'ST0567' },
      { name: 'Physiotherapist', level: 6, ref: 'ST0519' },
      { name: 'Podiatrist', level: 6, ref: 'ST0493' },
      { name: 'Prosthetist and orthotist', level: 6, ref: 'ST0601' },
      { name: 'Psychological wellbeing practitioner', level: 6, ref: 'ST0568' },
      { name: 'Public health practitioner - integrated degree', level: 6, ref: 'ST0631' },
      { name: 'Registered nurse degree (NMC 2018)', level: 6, ref: 'ST0781' },
      { name: 'Scientist', level: 6, ref: 'ST0626' },
      { name: 'Sonographer (integrated degree)', level: 6, ref: 'ST0554' },
      { name: 'Speech and language therapist', level: 6, ref: 'ST0618' },
      { name: 'Therapeutic radiographer', level: 6, ref: 'ST0620' },
      { name: 'Advanced clinical practitioner (integrated degree)', level: 7, ref: 'ST0564' },
      { name: 'Arts therapist', level: 7, ref: 'ST0633' },
      { name: 'Bioinformatics scientist (degree)', level: 7, ref: 'ST0649' },
      { name: 'Clinical associate in psychology (CAP) (integrated degree)', level: 7, ref: 'ST0820' },
      { name: 'Clinical pharmacology scientist (integrated degree)', level: 7, ref: 'ST0798' },
      { name: 'Clinical scientist', level: 7, ref: 'ST0893' },
      { name: 'Community nurse specialist practitioner (NMC 2022)', level: 7, ref: 'ST1419' },
      { name: 'Doctor (Degree)', level: 7, ref: 'ST0995' },
      { name: 'Health and care intelligence specialist', level: 7, ref: 'ST0830' },
      { name: 'Hydrogeologist (integrated degree)', level: 7, ref: 'ST1399' },
      { name: 'Medical statistician', level: 7, ref: 'ST0892' },
      { name: 'Optometrist', level: 7, ref: 'ST0773' },
      { name: 'Regulatory affairs specialist', level: 7, ref: 'ST0586' },
      { name: 'Research scientist', level: 7, ref: 'ST0759' },
      { name: 'Soil scientist', level: 7, ref: 'ST1362' },
      { name: 'Specialist community public health nurse (NMC 2022)', level: 7, ref: 'ST1418' },
      { name: 'Surgical care practitioner', level: 7, ref: 'ST1475' },
    ],
  },
  {
    route: 'Care services',
    standards: [
      { name: 'Adult care worker', level: 2, ref: 'ST0005' },
      { name: 'Playworker', level: 2, ref: 'ST0867' },
      { name: 'Lead adult care worker', level: 3, ref: 'ST0006' },
      { name: 'Safeguarding support officer', level: 3, ref: 'ST1030' },
      { name: 'Youth support worker', level: 3, ref: 'ST0906' },
      { name: 'Children, young people and families practitioner', level: 4, ref: 'ST0088' },
      { name: 'Domestic and sexual abuse support worker', level: 4, ref: 'ST0862' },
      { name: 'Early intervention practitioner', level: 4, ref: 'ST0868' },
      { name: 'Lead practitioner in adult care', level: 4, ref: 'ST0007' },
      { name: 'Children, young people and families manager', level: 5, ref: 'ST0087' },
      { name: 'Leader in adult care', level: 5, ref: 'ST0008' },
      { name: 'Social worker (integrated degree)', level: 6, ref: 'ST0510' },
      { name: 'Youth worker', level: 6, ref: 'ST0522' },
      { name: 'Play therapist', level: 7, ref: 'ST0905' },
    ],
  },
  {
    route: 'Education and early years',
    standards: [
      { name: 'Early years practitioner', level: 2, ref: 'ST0888' },
      { name: 'Early years educator', level: 3, ref: 'ST0135' },
      { name: 'Education technician (he assistant technician and simulation-based technician)', level: 3, ref: 'ST0666' },
      { name: 'Learning and skills assessor', level: 3, ref: 'ST1380' },
      { name: 'Teaching assistant', level: 3, ref: 'ST0454' },
      { name: 'Learning and skills mentor', level: 4, ref: 'ST1379' },
      { name: 'Early years lead practitioner', level: 5, ref: 'ST0551' },
      { name: 'Learning and skills teacher', level: 5, ref: 'ST0149' },
      { name: 'Specialist teaching assistant', level: 5, ref: 'ST1414' },
      { name: 'Teacher - Postgraduate', level: 6, ref: 'ST0490' },
      { name: 'Teacher - Undergraduate', level: 6, ref: 'ST1502' },
      { name: 'Academic professional', level: 7, ref: 'ST0477' },
      { name: 'Teacher for the sensory impaired', level: 7, ref: 'ST0966' },
    ],
  },
  {
    route: 'Business and administration',
    standards: [
      { name: 'Administration assistant', level: 2, ref: 'ST1472' },
      { name: 'Business administrator', level: 3, ref: 'ST0070' },
      { name: 'HR support', level: 3, ref: 'ST0239' },
      { name: 'Improvement technician', level: 3, ref: 'ST0193' },
      { name: 'Learning and development practitioner', level: 3, ref: 'ST0562' },
      { name: 'Leisure duty manager', level: 3, ref: 'ST0301' },
      { name: 'Library, information and archive services assistant', level: 3, ref: 'ST0664' },
      { name: 'Public sector compliance investigator and officer', level: 3, ref: 'ST0708' },
      { name: 'Public service operational delivery officer', level: 3, ref: 'ST0314' },
      { name: 'Recruiter', level: 3, ref: 'ST1421' },
      { name: 'Team leader', level: 3, ref: 'ST0384' },
      { name: 'Associate project manager', level: 4, ref: 'ST0310' },
      { name: 'Community energy specialist', level: 4, ref: 'ST0092' },
      { name: 'Corporate responsibility and sustainability practitioner', level: 4, ref: 'ST0934' },
      { name: 'Data protection and information governance practitioner', level: 4, ref: 'ST0967' },
      { name: 'Dental practice manager', level: 4, ref: 'ST0109' },
      { name: 'Employability practitioner', level: 4, ref: 'ST0663' },
      { name: 'Governance officer', level: 4, ref: 'ST1302' },
      { name: 'Improvement practitioner', level: 4, ref: 'ST0192' },
      { name: 'Information manager', level: 4, ref: 'ST0762' },
      { name: 'Junior management consultant', level: 4, ref: 'ST0273' },
      { name: 'Policy officer', level: 4, ref: 'ST0526' },
      { name: 'Quality practitioner', level: 4, ref: 'ST0853' },
      { name: 'Regulatory compliance officer', level: 4, ref: 'ST0430' },
      { name: 'Revenues and welfare benefits practitioner', level: 4, ref: 'ST0602' },
      { name: 'School business professional', level: 4, ref: 'ST0575' },
      { name: 'Coaching professional', level: 5, ref: 'ST0809' },
      { name: 'Improvement specialist', level: 5, ref: 'ST0555' },
      { name: 'Learning and development consultant business partner', level: 5, ref: 'ST0563' },
      { name: 'Operations manager', level: 5, ref: 'ST0385' },
      { name: 'People professional', level: 5, ref: 'ST0238' },
      { name: 'Career development professional', level: 6, ref: 'ST0694' },
      { name: 'Chartered manager (degree)', level: 6, ref: 'ST0272' },
      { name: 'Improvement leader', level: 6, ref: 'ST0556' },
      { name: 'Project manager (integrated degree)', level: 6, ref: 'ST0411' },
      { name: 'Service designer', level: 6, ref: 'ST0894' },
      { name: 'Social researcher', level: 6, ref: 'ST1341' },
      { name: 'Trading standards professional', level: 6, ref: 'ST0998' },
      { name: 'Library, information and knowledge management professional', level: 7, ref: 'ST1337' },
      { name: 'Operational research specialist', level: 7, ref: 'ST0884' },
      { name: 'Senior leader', level: 7, ref: 'ST0480' },
      { name: 'Senior people professional', level: 7, ref: 'ST0813' },
      { name: 'Sustainability business specialist (integrated degree)', level: 7, ref: 'ST0748' },
      { name: 'Systems thinking practitioner', level: 7, ref: 'ST0787' },
    ],
  },
  {
    route: 'Digital',
    standards: [
      { name: 'Cyber security technician', level: 3, ref: 'ST0865' },
      { name: 'Data technician', level: 3, ref: 'ST0795' },
      { name: 'Digital device repair technician', level: 3, ref: 'ST0682' },
      { name: 'Digital support technician', level: 3, ref: 'ST0120' },
      { name: 'IT solutions technician', level: 3, ref: 'ST0505' },
      { name: 'Information communications technician', level: 3, ref: 'ST0973' },
      { name: 'Network cable installer', level: 3, ref: 'ST0485' },
      { name: 'Radio network technician', level: 3, ref: 'ST0757' },
      { name: 'Software development technician', level: 3, ref: 'ST0128' },
      { name: 'Applications support lead', level: 4, ref: 'ST0949' },
      { name: 'Artificial intelligence (AI) and automation practitioner', level: 4, ref: 'ST1512' },
      { name: 'Business analyst', level: 4, ref: 'ST0117' },
      { name: 'Cyber security technologist (2021)', level: 4, ref: 'ST1021' },
      { name: 'Data analyst', level: 4, ref: 'ST0118' },
      { name: 'DevOps engineer', level: 4, ref: 'ST0825' },
      { name: 'Digital accessibility specialist', level: 4, ref: 'ST0863' },
      { name: 'Digital community manager', level: 4, ref: 'ST0345' },
      { name: 'Digital forensic technician', level: 4, ref: 'ST1343' },
      { name: 'Digital product manager', level: 4, ref: 'ST0964' },
      { name: 'Network engineer', level: 4, ref: 'ST0127' },
      { name: 'Software developer', level: 4, ref: 'ST0116' },
      { name: 'Software tester', level: 4, ref: 'ST0129' },
      { name: 'Data engineer', level: 5, ref: 'ST1386' },
      { name: 'Digital learning designer', level: 5, ref: 'ST0974' },
      { name: 'Creative digital design professional (integrated degree)', level: 6, ref: 'ST0625' },
      { name: 'Cyber security technical professional (integrated degree)', level: 6, ref: 'ST0409' },
      { name: 'Data scientist (integrated degree)', level: 6, ref: 'ST0585' },
      { name: 'Digital and technology solutions professional', level: 6, ref: 'ST0119' },
      { name: 'Digital user experience (UX) professional (integrated degree)', level: 6, ref: 'ST0470' },
      { name: 'Machine learning engineer', level: 6, ref: 'ST1398' },
      { name: 'Advanced digital forensic professional', level: 7, ref: 'ST1409' },
      { name: 'Artificial intelligence (AI) data specialist', level: 7, ref: 'ST0763' },
      { name: 'Digital and technology solutions specialist (integrated degree)', level: 7, ref: 'ST0482' },
      { name: 'Game programmer', level: 7, ref: 'ST0953' },
      { name: 'Spatial data specialist', level: 7, ref: 'ST0957' },
    ],
  },
  {
    route: 'Legal, finance and accounting',
    standards: [
      { name: 'Accounts or finance assistant', level: 2, ref: 'ST0608' },
      { name: 'Credit controller and collector', level: 2, ref: 'ST0176' },
      { name: 'Asset finance practitioner', level: 3, ref: 'ST0880' },
      { name: 'Assistant accountant', level: 3, ref: 'ST0002' },
      { name: 'Compliance and risk officer', level: 3, ref: 'ST0362' },
      { name: 'Financial services administrator', level: 3, ref: 'ST0177' },
      { name: 'Insurance practitioner', level: 3, ref: 'ST0240' },
      { name: 'Investment operations technician', level: 3, ref: 'ST0181' },
      { name: 'Mortgage adviser', level: 3, ref: 'ST0182' },
      { name: 'Motor finance specialist', level: 3, ref: 'ST0474' },
      { name: 'Paralegal', level: 3, ref: 'ST0245' },
      { name: 'Payroll administrator', level: 3, ref: 'ST0073' },
      { name: 'Pensions administrator', level: 3, ref: 'ST0187' },
      { name: 'Senior credit controller and debt collection specialist', level: 3, ref: 'ST0175' },
      { name: 'Senior financial services customer adviser', level: 3, ref: 'ST0185' },
      { name: 'Actuarial technician', level: 4, ref: 'ST0004' },
      { name: 'Insurance professional', level: 4, ref: 'ST0241' },
      { name: 'Internal audit technician', level: 4, ref: 'ST1484' },
      { name: 'Investment operations specialist', level: 4, ref: 'ST0180' },
      { name: 'Legal technician - conveyancing technician or probate technician', level: 4, ref: 'ST1312' },
      { name: 'Paraplanner and financial planner', level: 4, ref: 'ST1301' },
      { name: 'Professional accounting technician', level: 4, ref: 'ST0003' },
      { name: 'Professional taxation technician', level: 4, ref: 'ST1458' },
      { name: 'Treasury assistant', level: 4, ref: 'ST1485' },
      { name: 'Advanced paralegal', level: 5, ref: 'ST1476' },
      { name: 'Payroll assistant manager', level: 5, ref: 'ST0869' },
      { name: 'Accounting finance manager', level: 6, ref: 'ST1303' },
      { name: 'Actuarial analyst', level: 6, ref: 'ST1473' },
      { name: 'Certified internal auditor', level: 6, ref: 'ST1487' },
      { name: 'Chartered legal executive', level: 6, ref: 'ST0244' },
      { name: 'Corporate treasurer', level: 6, ref: 'ST1468' },
      { name: 'Costs lawyer', level: 6, ref: 'ST1400' },
      { name: 'Financial services professional', level: 6, ref: 'ST0472' },
      { name: 'Licensed conveyancer or licensed probate practitioner', level: 6, ref: 'ST1311' },
      { name: 'Patent scientist or patent engineer', level: 6, ref: 'ST1454' },
      { name: 'Professional economist (integrated degree)', level: 6, ref: 'ST0603' },
      { name: 'Senior compliance and risk specialist', level: 6, ref: 'ST0363' },
      { name: 'Senior insurance professional', level: 6, ref: 'ST0520' },
      { name: 'Accountancy or taxation professional', level: 7, ref: 'ST0001' },
      { name: 'Actuary', level: 7, ref: 'ST0502' },
      { name: 'Barrister', level: 7, ref: 'ST1389' },
      { name: 'Chartered legal executive litigator and advocate', level: 7, ref: 'ST1368' },
      { name: 'Chartered tax advisor', level: 7, ref: 'ST1459' },
      { name: 'Internal audit professional', level: 7, ref: 'ST0610' },
      { name: 'Senior investment and commercial banking professional', level: 7, ref: 'ST0561' },
      { name: 'Senior professional economist (integrated degree)', level: 7, ref: 'ST0796' },
      { name: 'Solicitor', level: 7, ref: 'ST0246' },
    ],
  },
  {
    route: 'Sales, marketing and procurement',
    standards: [
      { name: 'Butcher', level: 2, ref: 'ST0078' },
      { name: 'Customer service practitioner', level: 2, ref: 'ST0072' },
      { name: 'Fishmonger', level: 2, ref: 'ST0194' },
      { name: 'Funeral team member', level: 2, ref: 'ST0594' },
      { name: 'Housing and property management assistant', level: 2, ref: 'ST0235' },
      { name: 'Junior estate agent', level: 2, ref: 'ST0329' },
      { name: 'Retailer', level: 2, ref: 'ST0327' },
      { name: 'Trade supplier', level: 2, ref: 'ST0334' },
      { name: 'Advanced butcher', level: 3, ref: 'ST0077' },
      { name: 'Advertising and media executive', level: 3, ref: 'ST0644' },
      { name: 'Bid and proposal co-ordinator', level: 3, ref: 'ST0056' },
      { name: 'Customer service specialist', level: 3, ref: 'ST0071' },
      { name: 'Event assistant', level: 3, ref: 'ST0168' },
      { name: 'Fundraiser', level: 3, ref: 'ST0887' },
      { name: 'Funeral director', level: 3, ref: 'ST0584' },
      { name: 'Housing and property management', level: 3, ref: 'ST0234' },
      { name: 'IT technical salesperson', level: 3, ref: 'ST0115' },
      { name: 'Multi-channel marketer', level: 3, ref: 'ST1031' },
      { name: 'Procurement and supply assistant', level: 3, ref: 'ST0810' },
      { name: 'Travel consultant', level: 3, ref: 'ST0340' },
      { name: 'Buying and merchandising assistant', level: 4, ref: 'ST0683' },
      { name: 'Market research executive', level: 4, ref: 'ST0883' },
      { name: 'Marketing executive', level: 4, ref: 'ST0596' },
      { name: 'Procurement and supply chain practitioner', level: 4, ref: 'ST0313' },
      { name: 'Public relations and communications assistant', level: 4, ref: 'ST0311' },
      { name: 'Retail manager', level: 4, ref: 'ST0325' },
      { name: 'Sales executive', level: 4, ref: 'ST0572' },
      { name: 'Senior housing and property management', level: 4, ref: 'ST0236' },
      { name: 'Assistant buyer and merchandiser', level: 6, ref: 'ST0668' },
      { name: 'Business to business sales professional (integrated degree)', level: 6, ref: 'ST0423' },
      { name: 'Digital marketer (integrated degree)', level: 6, ref: 'ST0481' },
      { name: 'Marketing manager', level: 6, ref: 'ST0612' },
      { name: 'Retail leadership (integrated degree)', level: 6, ref: 'ST0547' },
      { name: 'Senior procurement and supply chain professional', level: 6, ref: 'ST0811' },
    ],
  },
  {
    route: 'Agriculture, environmental and animal care',
    standards: [
      { name: 'Animal care and welfare assistant', level: 2, ref: 'ST0397' },
      { name: 'Arborist', level: 2, ref: 'ST0223' },
      { name: 'Countryside worker', level: 2, ref: 'ST0408' },
      { name: 'Dog groomer', level: 2, ref: 'ST0943' },
      { name: 'Equine groom', level: 2, ref: 'ST0166' },
      { name: 'Fisher', level: 2, ref: 'ST0952' },
      { name: 'Florist', level: 2, ref: 'ST0538' },
      { name: 'General farm worker', level: 2, ref: 'ST0937' },
      { name: 'Golf greenkeeper', level: 2, ref: 'ST0209' },
      { name: 'Horticulture or landscape construction operative', level: 2, ref: 'ST0225' },
      { name: 'Land-based service engineer', level: 2, ref: 'ST0242' },
      { name: 'Poultry worker', level: 2, ref: 'ST0389' },
      { name: 'Sports turf operative', level: 2, ref: 'ST0210' },
      { name: 'Underkeeper', level: 2, ref: 'ST0412' },
      { name: 'Veterinary Care Assistant', level: 2, ref: 'ST1446' },
      { name: 'Advanced sports turf technician', level: 3, ref: 'ST1323' },
      { name: 'Animal care and welfare manager', level: 3, ref: 'ST1359' },
      { name: 'Crop technician', level: 3, ref: 'ST0018' },
      { name: 'Detection and protection working dog specialist', level: 3, ref: 'ST1298' },
      { name: 'Farrier', level: 3, ref: 'ST0172' },
      { name: 'Forest craftsperson', level: 3, ref: 'ST1321' },
      { name: 'Horticulture or landscaping supervisor', level: 3, ref: 'ST0226' },
      { name: 'Keeper and aquarist', level: 3, ref: 'ST0789' },
      { name: 'Land-based service engineering technician', level: 3, ref: 'ST0243' },
      { name: 'Livestock unit technician', level: 3, ref: 'ST0938' },
      { name: 'Poultry technician', level: 3, ref: 'ST0467' },
      { name: 'Senior equine groom', level: 3, ref: 'ST0167' },
      { name: 'Senior florist', level: 3, ref: 'ST1335' },
      { name: 'Veterinary nurse', level: 3, ref: 'ST0343' },
      { name: 'Water environment worker', level: 3, ref: 'ST0767' },
      { name: 'Animal training instructor', level: 4, ref: 'ST0398' },
      { name: 'Arboriculturist', level: 4, ref: 'ST0921' },
      { name: 'Assistant ecologist', level: 4, ref: 'ST1474' },
      { name: 'Assistant farm manager', level: 4, ref: 'ST1320' },
      { name: 'Countryside ranger', level: 4, ref: 'ST0926' },
      { name: 'Forestry works manager', level: 4, ref: 'ST1427' },
      { name: 'Golf course manager', level: 5, ref: 'ST0208' },
      { name: 'Horticulture and landscaping technical manager', level: 5, ref: 'ST0924' },
      { name: 'Sports Turf Technical Manager', level: 5, ref: 'ST1410' },
      { name: 'Vet technician (livestock)', level: 5, ref: 'ST0946' },
      { name: 'Environmental practitioner (Degree)', level: 6, ref: 'ST0778' },
      { name: 'Professional arboriculturist', level: 6, ref: 'ST0922' },
      { name: 'Professional forester (integrated degree)', level: 6, ref: 'ST0923' },
      { name: 'Ecologist (integrated degree)', level: 7, ref: 'ST0577' },
    ],
  },
  {
    route: 'Transport and logistics',
    standards: [
      { name: 'Aviation customer service operative', level: 2, ref: 'ST0907' },
      { name: 'Aviation ground operative', level: 2, ref: 'ST0037' },
      { name: 'Express delivery operative', level: 2, ref: 'ST0103' },
      { name: 'Express delivery sortation hub operative', level: 2, ref: 'ST0753' },
      { name: 'Large goods vehicle (LGV) driver C + E', level: 2, ref: 'ST0257' },
      { name: 'Marina and boatyard operative', level: 2, ref: 'ST0592' },
      { name: 'Passenger transport driver - bus and coach or tram', level: 2, ref: 'ST0338' },
      { name: 'Passenger transport operative', level: 2, ref: 'ST0339' },
      { name: 'Port operative', level: 2, ref: 'ST0307' },
      { name: 'Removals operative', level: 2, ref: 'ST1393' },
      { name: 'Seafarer (deck rating)', level: 2, ref: 'ST0274' },
      { name: 'Supply chain warehouse operative', level: 2, ref: 'ST0259' },
      { name: 'Traffic operator', level: 2, ref: 'ST1394' },
      { name: 'Urban driver', level: 2, ref: 'ST1025' },
      { name: 'Aviation flight operations coordinator', level: 3, ref: 'ST1007' },
      { name: 'Aviation ground specialist', level: 3, ref: 'ST0038' },
      { name: 'Aviation movement specialist', level: 3, ref: 'ST0954' },
      { name: 'Boatmaster', level: 3, ref: 'ST0621' },
      { name: 'Cabin crew', level: 3, ref: 'ST0558' },
      { name: 'International freight forwarding specialist', level: 3, ref: 'ST0539' },
      { name: 'Officer of the watch (near coastal)', level: 3, ref: 'ST0842' },
      { name: 'Rail infrastructure operator', level: 3, ref: 'ST1378' },
      { name: 'Small commercial vessel crewmember', level: 3, ref: 'ST0400' },
      { name: 'Supply chain practitioner (fast-moving consumer goods (FMCG))', level: 3, ref: 'ST0201' },
      { name: 'Train driver', level: 3, ref: 'ST0645' },
      { name: 'Transport and warehouse operations supervisor', level: 3, ref: 'ST0647' },
      { name: 'Transport scheduler', level: 3, ref: 'ST1438' },
      { name: 'Aviation operations manager', level: 4, ref: 'ST0039' },
      { name: 'Jack-up barge master - non-propelled unit', level: 4, ref: 'ST1336' },
      { name: 'Passenger transport operations manager', level: 4, ref: 'ST0337' },
      { name: 'Port marine operations officer', level: 4, ref: 'ST0428' },
      { name: 'Ship’s master – less than 500 gross tonnage near coastal', level: 4, ref: 'ST1333' },
      { name: 'Air traffic controller', level: 5, ref: 'ST0595' },
      { name: 'Marine pilot', level: 5, ref: 'ST0427' },
      { name: 'Uncrewed marine vehicle specialist', level: 5, ref: 'ST0975' },
      { name: 'Express delivery manager (degree)', level: 6, ref: 'ST0471' },
      { name: 'Railway operations manager', level: 6, ref: 'ST1441' },
      { name: 'Supply chain leadership professional (integrated degree)', level: 6, ref: 'ST0548' },
    ],
  },
  {
    route: 'Catering and hospitality',
    standards: [
      { name: 'Baker', level: 2, ref: 'ST0191' },
      { name: 'Commis chef', level: 2, ref: 'ST0228' },
      { name: 'Food and beverage team member', level: 2, ref: 'ST1488' },
      { name: 'Hospitality accommodation team member', level: 2, ref: 'ST1420' },
      { name: 'Production chef', level: 2, ref: 'ST0589' },
      { name: 'Chef de partie', level: 3, ref: 'ST0227' },
      { name: 'Hospitality supervisor', level: 3, ref: 'ST0230' },
      { name: 'Lead baker', level: 3, ref: 'ST1349' },
      { name: 'Pastry chef', level: 3, ref: 'ST0929' },
      { name: 'Senior production chef', level: 3, ref: 'ST0232' },
      { name: 'Hospitality manager', level: 4, ref: 'ST0229' },
      { name: 'Senior culinary chef', level: 4, ref: 'ST0864' },
    ],
  },
  {
    route: 'Hair and beauty',
    standards: [
      { name: 'Barbering professional', level: 2, ref: 'ST1273' },
      { name: 'Beauty therapist', level: 2, ref: 'ST0630' },
      { name: 'Hairdressing professional', level: 2, ref: 'ST0213' },
      { name: 'Nail services technician', level: 2, ref: 'ST0635' },
      { name: 'Advanced and creative hair professional', level: 3, ref: 'ST0214' },
      { name: 'Advanced beauty therapist', level: 3, ref: 'ST0211' },
      { name: 'Wellbeing and holistic therapist', level: 3, ref: 'ST0685' },
      { name: 'Aesthetic practitioner - skin rejuvenation', level: 5, ref: 'ST1238' },
    ],
  },
  {
    route: 'Creative and design',
    standards: [
      { name: 'Junior grip', level: 2, ref: 'ST1318' },
      { name: 'Leather craftsperson', level: 2, ref: 'ST0460' },
      { name: 'Archaeological technician', level: 3, ref: 'ST0221' },
      { name: 'Art market coordinator', level: 3, ref: 'ST1450' },
      { name: 'Bespoke furniture maker', level: 3, ref: 'ST0639' },
      { name: 'Bespoke saddler', level: 3, ref: 'ST0328' },
      { name: 'Blacksmith', level: 3, ref: 'ST0378' },
      { name: 'Broadcast and media systems technical operator', level: 3, ref: 'ST0424' },
      { name: 'Clock maker', level: 3, ref: 'ST0447' },
      { name: 'Collections technician', level: 3, ref: 'ST1469' },
      { name: 'Content creator', level: 3, ref: 'ST0105' },
      { name: 'Costume technician - stage and screen', level: 3, ref: 'ST0783' },
      { name: 'Craft technician', level: 3, ref: 'ST0919' },
      { name: 'Creative industries production technician', level: 3, ref: 'ST1297' },
      { name: 'Cultural learning and participation officer', level: 3, ref: 'ST0396' },
      { name: 'Furniture restorer', level: 3, ref: 'ST0978' },
      { name: 'Garment maker', level: 3, ref: 'ST0846' },
      { name: 'Hair, wigs, make-up and prosthetics technician', level: 3, ref: 'ST0918' },
      { name: 'Jewellery, silversmithing, and allied trades professional', level: 3, ref: 'ST0439' },
      { name: 'Junior advertising creative', level: 3, ref: 'ST0925' },
      { name: 'Music business co-ordinator', level: 3, ref: 'ST1449' },
      { name: 'Musical instrument maintenance and repair technician', level: 3, ref: 'ST1440' },
      { name: 'Production assistant - screen and audio', level: 3, ref: 'ST0341' },
      { name: 'Scenic artist', level: 3, ref: 'ST0916' },
      { name: 'Scenic automation technician', level: 3, ref: 'ST0915' },
      { name: 'Scenic construction technician', level: 3, ref: 'ST0917' },
      { name: 'Watchmaker', level: 3, ref: 'ST0395' },
      { name: 'Assistant recording technician', level: 4, ref: 'ST0944' },
      { name: 'Historic environment advice assistant', level: 4, ref: 'ST0749' },
      { name: 'Junior animator', level: 4, ref: 'ST0488' },
      { name: 'Junior production coordinator', level: 4, ref: 'ST0792' },
      { name: 'Junior visual effects - VFX artist or assistant technical director - ATD', level: 4, ref: 'ST1325' },
      { name: 'Photographer', level: 4, ref: 'ST1388' },
      { name: 'Post production technical operator', level: 4, ref: 'ST0696' },
      { name: 'Publishing professional', level: 4, ref: 'ST1442' },
      { name: 'Stained glass craftsperson', level: 4, ref: 'ST0912' },
      { name: 'Audiovisual technician', level: 5, ref: 'ST0940' },
      { name: 'Bespoke cutter and tailor', level: 5, ref: 'ST0055' },
      { name: 'Journalist', level: 5, ref: 'ST1324' },
      { name: 'Advertising creative', level: 6, ref: 'ST1340' },
      { name: 'Broadcast and media systems engineer (integrated degree)', level: 6, ref: 'ST0426' },
      { name: 'Interior designer', level: 6, ref: 'ST1361' },
      { name: 'Living and commercial spaces designer', level: 6, ref: 'ST0965' },
      { name: 'Model maker', level: 6, ref: 'ST1371' },
      { name: 'Registrar (creative and cultural)', level: 6, ref: 'ST0590' },
      { name: 'Archaeological specialist (degree)', level: 7, ref: 'ST0769' },
      { name: 'Archivist and records manager', level: 7, ref: 'ST0904' },
      { name: 'Creative industries production manager', level: 7, ref: 'ST0525' },
      { name: 'Cultural heritage conservator (degree)', level: 7, ref: 'ST0628' },
      { name: 'Curator', level: 7, ref: 'ST0782' },
      { name: 'Historic environment advisor', level: 7, ref: 'ST0831' },
      { name: 'Senior journalist', level: 7, ref: 'ST0286' },
    ],
  },
  {
    route: 'Protective services',
    standards: [
      { name: 'HM forces serviceperson (protective services)', level: 2, ref: 'ST0222' },
      { name: 'Professional security operative', level: 2, ref: 'ST1016' },
      { name: 'Community fire safety advisor', level: 3, ref: 'ST0593' },
      { name: 'Custody and detention professional', level: 3, ref: 'ST0386' },
      { name: 'Emergency contact handler', level: 3, ref: 'ST0483' },
      { name: 'Fire safety advisor', level: 3, ref: 'ST0188' },
      { name: 'Operational firefighter', level: 3, ref: 'ST0486' },
      { name: 'Probation service practitioner', level: 3, ref: 'ST0494' },
      { name: 'Safety, health and environment technician', level: 3, ref: 'ST0550' },
      { name: 'Security first line manager', level: 3, ref: 'ST0330' },
      { name: 'Anti-social behaviour and community safety officer', level: 4, ref: 'ST0930' },
      { name: 'Counter fraud investigator', level: 4, ref: 'ST0747' },
      { name: 'Fire safety inspector', level: 4, ref: 'ST0746' },
      { name: 'Fraud control specialist', level: 4, ref: 'ST1445' },
      { name: 'Intelligence analyst', level: 4, ref: 'ST0516' },
      { name: 'Non home office police officer', level: 4, ref: 'ST0764' },
      { name: 'Police community support officer', level: 4, ref: 'ST0509' },
      { name: 'Protective security adviser', level: 4, ref: 'ST1401' },
      { name: 'Youth justice practitioner', level: 5, ref: 'ST0878' },
      { name: 'Police constable (integrated degree)', level: 6, ref: 'ST0304' },
      { name: 'Resilience and emergencies professional', level: 6, ref: 'ST1322' },
      { name: 'Serious and complex crime investigator (integrated degree)', level: 6, ref: 'ST0512' },
    ],
  },
]

export const ALL_STANDARDS = APPRENTICESHIP_STANDARDS.flatMap(r =>
  r.standards.map(s => ({ ...s, route: r.route }))
)